// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/audio_service.proto

package apiv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AudioRequest struct {
	AudioData            []byte   `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioRequest) Reset()         { *m = AudioRequest{} }
func (m *AudioRequest) String() string { return proto.CompactTextString(m) }
func (*AudioRequest) ProtoMessage()    {}
func (*AudioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f09e7e9b693874fb, []int{0}
}

func (m *AudioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioRequest.Unmarshal(m, b)
}
func (m *AudioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioRequest.Marshal(b, m, deterministic)
}
func (m *AudioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioRequest.Merge(m, src)
}
func (m *AudioRequest) XXX_Size() int {
	return xxx_messageInfo_AudioRequest.Size(m)
}
func (m *AudioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AudioRequest proto.InternalMessageInfo

func (m *AudioRequest) GetAudioData() []byte {
	if m != nil {
		return m.AudioData
	}
	return nil
}

type AudioResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioResponse) Reset()         { *m = AudioResponse{} }
func (m *AudioResponse) String() string { return proto.CompactTextString(m) }
func (*AudioResponse) ProtoMessage()    {}
func (*AudioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f09e7e9b693874fb, []int{1}
}

func (m *AudioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioResponse.Unmarshal(m, b)
}
func (m *AudioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioResponse.Marshal(b, m, deterministic)
}
func (m *AudioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioResponse.Merge(m, src)
}
func (m *AudioResponse) XXX_Size() int {
	return xxx_messageInfo_AudioResponse.Size(m)
}
func (m *AudioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AudioResponse proto.InternalMessageInfo

func (m *AudioResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AudioRequest)(nil), "audio.AudioRequest")
	proto.RegisterType((*AudioResponse)(nil), "audio.AudioResponse")
}

func init() { proto.RegisterFile("api/v1/audio_service.proto", fileDescriptor_f09e7e9b693874fb) }

var fileDescriptor_f09e7e9b693874fb = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0xcf, 0x82, 0x30,
	0x10, 0xc5, 0xc3, 0xf0, 0x7d, 0x86, 0x8a, 0x4b, 0x75, 0x20, 0x44, 0x8d, 0x61, 0xc2, 0x41, 0x08,
	0xba, 0xb9, 0x69, 0x9c, 0x1c, 0x61, 0x73, 0x21, 0x27, 0xbd, 0x98, 0x0e, 0xd8, 0x7a, 0x2d, 0xfc,
	0xfd, 0xc6, 0x02, 0x89, 0x6e, 0x77, 0xbf, 0xbc, 0xbc, 0x5f, 0x1e, 0x8b, 0x40, 0xcb, 0xac, 0xcb,
	0x33, 0x68, 0x85, 0x54, 0x95, 0x41, 0xea, 0x64, 0x8d, 0xa9, 0x26, 0x65, 0x15, 0xff, 0x73, 0x30,
	0xde, 0xb1, 0xe0, 0xf4, 0x39, 0x0a, 0x7c, 0xb5, 0x68, 0x2c, 0x5f, 0x31, 0xd6, 0xa7, 0x05, 0x58,
	0x08, 0xbd, 0x8d, 0x97, 0x04, 0x85, 0xef, 0xc8, 0x05, 0x2c, 0xc4, 0x5b, 0x36, 0x1b, 0xe2, 0x46,
	0xab, 0xa7, 0x41, 0x1e, 0xb2, 0x49, 0x83, 0xc6, 0xc0, 0x03, 0x5d, 0xd8, 0x2f, 0xc6, 0x77, 0x7f,
	0x1d, 0x9a, 0xcb, 0x5e, 0xcb, 0x8f, 0x6c, 0x5a, 0x5a, 0x42, 0x68, 0x1c, 0xe5, 0xf3, 0xd4, 0xb5,
	0xa6, 0xdf, 0xf6, 0x68, 0xf1, 0x0b, 0x7b, 0x47, 0xe2, 0x9d, 0xd7, 0xb7, 0xa5, 0x50, 0xb5, 0x55,
	0x54, 0x11, 0xd6, 0x8a, 0x04, 0x52, 0x36, 0x4e, 0xd3, 0xb2, 0xcb, 0xef, 0xff, 0x6e, 0xd3, 0xe1,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xeb, 0x84, 0xf4, 0xf1, 0x00, 0x00, 0x00,
}
